components:
  schemas:
    検査実施人数:
      description: PCR検査を受けた人の数を日別に集計したデータ
      required:
        - 実施_年月日
        - 都道府県名
        - 市区町村名
        - 検査実施_人数
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#検査実施人数
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
      type: object
      properties:
        実施_年月日:
          description: "検査を実施した年月日を記載。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/DateTime
            uri: http://cio-context.fiware-testbed.jp/dataset#実施_年月日
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: string
          format: date
        全国地方公共団体コード:
          description: "総務省の定める全国地方公共団体コード（6桁コード）を記載。6桁に満たない場合、先頭は0埋めとする。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: http://cio-context.fiware-testbed.jp/dataset#全国地方公共団体コード
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: string
        都道府県名:
          description: "情報の管理主体である地方公共団体名について、都道府県名を記載。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: http://cio-context.fiware-testbed.jp/dataset#都道府県名
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: string
        市区町村名:
          description: "情報の管理主体である地方公共団体名について、市区町村名を記載。※都道府県については記載不要。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: http://cio-context.fiware-testbed.jp/dataset#市区町村名
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: string
        検査実施_人数:
          description: "検査を受けた人の数を記載。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Number
            uri: http://cio-context.fiware-testbed.jp/dataset#検査実施_人数
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: number
        備考:
          description: "備考があれば記載。"
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: http://cio-context.fiware-testbed.jp/dataset#備考
            uri-prefix: http://cio-context.fiware-testbed.jp/dataset#
          type: string
info:
  title: "新型コロナウイルス感染症対策に関するオープンデータ項目定義"
  description: "Code for Japanにより策定された新型コロナウイルス感染症対策に関するオープンデータ項目定義"
  version: "1.0.0"
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        ? "200"
        :
          description:  OK
          content:
            application/ld+json:
              schema:
                type: object
