---
components:
  schemas:
    陽性患者属性:
      allOf:
        - $ref: "./01_陽性患者属性/model.yaml#/components/schemas/陽性患者属性"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#陽性患者属性
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
    検査実施人数:
      allOf:
        - $ref: "./02_検査実施人数/model.yaml#/components/schemas/検査実施人数"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#検査実施人数
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
    検査実施件数:
      allOf:
        - $ref: "./03_検査実施件数/model.yaml#/components/schemas/検査実施件数"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#検査実施件数
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
    陰性確認数:
      allOf:
        - $ref: "./04_陰性確認数/model.yaml#/components/schemas/陰性確認数"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#陰性確認数
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
    コールセンター相談件数:
      allOf:
        - $ref: "./05_コールセンター相談件数/model.yaml#/components/schemas/コールセンター相談件数"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#コールセンター相談件数
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
    支援制度:
      allOf:
        - $ref: "./06_支援制度/model.yaml#/components/schemas/支援制度"
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#支援制度
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
info:
  title: "新型コロナウイルス感染症対策に関するオープンデータ項目定義"
  description: "Code for Japanにより策定された新型コロナウイルス感染症対策に関するオープンデータ項目定義"
  version: "1.0.0"
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        ? "200"
        :
          description:  OK
          content:
            application/ld+json:
              schema:
                type: object

