components:
  schemas:
    公衆無線LANアクセスポイント一覧:
      description: 公衆無線LANアクセスポイントの一覧。
      required:
      - 名称
      - 名称_カナ
      - 住所
      x-ngsi:
        uri: https://cio-context.fiware-testbed.jp/dataset#公衆無線LANアクセスポイント一覧
        uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
      type: object
      properties:
        都道府県コード又は市区町村コード:
          description: 情報の管理主体である地方公共団体の都道府県コード又は市区町村コードを記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#都道府県コード又は市区町村コード
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        'NO':
          description: 情報の管理主体である地方公共団体内でデータが一意に決まるよう、NOを設定し記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#NO
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        都道府県名:
          description: 情報の管理主体である地方公共団体名について、都道府県名を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#都道府県名
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        市区町村名:
          description: 情報の管理主体である地方公共団体名について、市区町村名を記載。都道府県については記載不要。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#市区町村名
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        名称:
          description: 公衆無線LANの設置場所の通称や建物等の名前を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#名称
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        名称_カナ:
          description: 公衆無線LANの設置場所の通称や建物等の名前をカナで記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#名称_カナ
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        名称_英語:
          description: 公衆無線LANの設置場所の通称や建物等の名前を英語で記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#名称_英語
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        住所:
          description: 公衆無線LANの設置場所の住所を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#住所
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        方書:
          description: 公衆無線LANの設置場所の住所の方書を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#方書
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        緯度:
          description: 公衆無線LANの設置場所の緯度を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Number
            uri: https://cio-context.fiware-testbed.jp/dataset#緯度
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: number
        経度:
          description: 公衆無線LANの設置場所の経度を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Number
            uri: https://cio-context.fiware-testbed.jp/dataset#経度
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: number
        設置者:
          description: 公衆無線LANの設置組織を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#設置者
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        電話番号:
          description: 公衆無線LANの設置施設の連絡先（電話番号）を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#電話番号
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        内線番号:
          description: 公衆無線LANの設置施設の連絡先（内線番号）を記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#内線番号
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        SSID:
          description: 公衆無線LANのSSIDを記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#SSID
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        提供エリア:
          description: 公衆無線LANの設置施設の施設内の提供エリアを記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#提供エリア
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        URL:
          description: 公衆無線LANの設置施設のWebサイトのURLを記載。
          x-ngsi:
            attr-type: Property
            model: https://schema.org/URL
            uri: https://cio-context.fiware-testbed.jp/dataset#URL
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
          format: uri
        備考:
          description: 特記事項があれば記載。（利用条件等）
          x-ngsi:
            attr-type: Property
            model: https://schema.org/Text
            uri: https://cio-context.fiware-testbed.jp/dataset#備考
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: string
        location:
          description: location
          x-ngsi:
            attr-type: GeoProperty
            model: https://schema.org/StructuredValue
            uri: https://cio-context.fiware-testbed.jp/dataset#location
            uri-prefix: https://cio-context.fiware-testbed.jp/dataset#
          type: object
          allOf:
          - $ref: https://geojson.org/schema/Geometry.json
info:
  title: "推奨データセット"
  description: "政府CIOポータルで推奨データセットとして選定されたデータセットのデータ項目定義"
  version: "1.0.0"
openapi: "3.0.0"
paths:
  /ngsi-ld/v1/entities:
    get:
      responses:
        ? "200"
        :
          description:  OK
          content:
            application/ld+json:
              schema:
                type: object
